---
abstract: 'Run HTTP tests on external live servers'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Test-ExternalServer
requires:
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Plack::Loader: 0
  Plack::Test: 0
  Test::More: 0.89
  Test::TCP: 0
  URI: 0
version: 0.01
